package com.example.pomofocus

object Constants {
    const val FOCUS_TIMER = 10
    const val SHORT_BREAK_TIMER = 5
    const val LONG_BREAK_TIMER = 15

    const val NOTIFICATION_CHANNEL_ID = "POMOFOCUS_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "POMOFOCUS_NOTIFICATION"
    const val NOTIFICATION_ID = 10

    const val TIMER_STATE = "TIMER_STATE"

    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_PAUSE = "ACTION_SERVICE_PAUSE"
    const val ACTION_SERVICE_RESUME = "ACTION_SERVICE_RESUME"
    const val ACTION_SERVICE_FINISH = "ACTION_SERVICE_FINISH"

    const val CLICK_REQUEST_CODE = 100
    const val FINISH_REQUEST_CODE = 101
    const val PAUSE_REQUEST_CODE = 102
    const val RESUME_REQUEST_CODE = 103
}